// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsApp1.Repositories;

#nullable disable

namespace WinFormsApp1.Migrations
{
    [DbContext(typeof(InvEntities))]
    partial class InvEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WinFormsApp1.Repositories.Models.ImageAndFp", b =>
                {
                    b.Property<int>("Serial")
                        .HasColumnType("int")
                        .HasColumnName("serial");

                    b.Property<int>("Serpers")
                        .HasColumnType("int")
                        .HasColumnName("serpers");

                    b.Property<byte[]>("Facefront")
                        .HasColumnType("image")
                        .HasColumnName("facefront");

                    b.Property<byte[]>("Faceleft")
                        .HasColumnType("image")
                        .HasColumnName("faceleft");

                    b.Property<byte[]>("Faceright")
                        .HasColumnType("image")
                        .HasColumnName("faceright");

                    b.Property<byte[]>("Fpleft")
                        .HasColumnType("image")
                        .HasColumnName("fpleft");

                    b.Property<byte[]>("Fpright")
                        .HasColumnType("image")
                        .HasColumnName("fpright");

                    b.HasKey("Serial", "Serpers")
                        .HasName("PK__ImageAnd__C87A60D5C4BE05D5");

                    b.ToTable("ImageAndFP");
                });

            modelBuilder.Entity("WinFormsApp1.Repositories.Models.ImageFace", b =>
                {
                    b.Property<int>("Serial")
                        .HasColumnType("int")
                        .HasColumnName("SERIAL");

                    b.Property<int>("Serpers")
                        .HasColumnType("int")
                        .HasColumnName("SERPERS");

                    b.Property<byte[]>("Facefront")
                        .HasColumnType("image")
                        .HasColumnName("facefront");

                    b.Property<byte[]>("Faceleft")
                        .HasColumnType("image")
                        .HasColumnName("faceleft");

                    b.Property<byte[]>("Faceright")
                        .HasColumnType("image")
                        .HasColumnName("faceright");

                    b.HasKey("Serial", "Serpers")
                        .HasName("PK__ImageFac__52B352DE3D04902C");

                    b.ToTable("ImageFace");
                });

            modelBuilder.Entity("WinFormsApp1.Repositories.Models.ImageFp", b =>
                {
                    b.Property<int>("Serial")
                        .HasColumnType("int")
                        .HasColumnName("SERIAL");

                    b.Property<int>("Serpers")
                        .HasColumnType("int")
                        .HasColumnName("SERPERS");

                    b.Property<byte[]>("Fpleft")
                        .HasColumnType("image")
                        .HasColumnName("fpleft");

                    b.Property<byte[]>("Fpright")
                        .HasColumnType("image")
                        .HasColumnName("fpright");

                    b.HasKey("Serial", "Serpers")
                        .HasName("PK__ImageFP__52B352DE842C54E2");

                    b.ToTable("ImageFP");
                });

            modelBuilder.Entity("WinFormsApp1.Repositories.Models.Invest", b =>
                {
                    b.Property<int>("Serial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SERIAL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Serial"));

                    b.Property<string>("Crime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CRIME");

                    b.Property<DateOnly>("Dfile")
                        .HasColumnType("date")
                        .HasColumnName("DFILE");

                    b.Property<DateOnly>("Dmahdar")
                        .HasColumnType("date")
                        .HasColumnName("DMAHDAR");

                    b.Property<string>("Madbout")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("MADBOUT");

                    b.Property<string>("Rem")
                        .HasColumnType("text")
                        .HasColumnName("REM");

                    b.Property<string>("Resume")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("RESUME");

                    b.HasKey("Serial")
                        .HasName("PK__INVEST__1CE6D4E6353FDDFC");

                    b.ToTable("INVEST");
                });

            modelBuilder.Entity("WinFormsApp1.Repositories.Models.Invperson", b =>
                {
                    b.Property<int>("Serial")
                        .HasColumnType("int")
                        .HasColumnName("SERIAL");

                    b.Property<int>("Serpers")
                        .HasColumnType("int")
                        .HasColumnName("SERPERS");

                    b.Property<string>("Adrs")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ADRS");

                    b.Property<int?>("Arch")
                        .HasColumnType("int")
                        .HasColumnName("ARCH");

                    b.Property<int?>("Attr")
                        .HasColumnType("int")
                        .HasColumnName("ATTR");

                    b.Property<int?>("Dbirth")
                        .HasColumnType("int")
                        .HasColumnName("DBIRTH");

                    b.Property<int?>("Exst")
                        .HasColumnType("int")
                        .HasColumnName("EXST");

                    b.Property<string>("Father")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FATHER");

                    b.Property<string>("Fname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FNAME");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Idnum")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LNAME");

                    b.Property<string>("Mobileno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mother")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MOTHER");

                    b.Property<int?>("Nation")
                        .HasColumnType("int")
                        .HasColumnName("NATION");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pbirth")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PBIRTH");

                    b.Property<string>("Reg")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("REG");

                    b.Property<string>("Resid")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("RESID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Serial", "Serpers")
                        .HasName("PK__invperso__52B352DEC229374F");

                    b.ToTable("invpersons");
                });

            modelBuilder.Entity("WinFormsApp1.Repositories.Models.Nation", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int")
                        .HasColumnName("CODE");

                    b.Property<string>("Alabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ALABEL");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FNAME");

                    b.Property<int>("Grp")
                        .HasColumnType("int")
                        .HasColumnName("GRP");

                    b.Property<string>("Llabel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LLABEL");

                    b.Property<int>("Lng")
                        .HasColumnType("int")
                        .HasColumnName("LNG");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("TYPE");

                    b.HasKey("Code")
                        .HasName("PK__nations__AA1D437898E5A570");

                    b.ToTable("nations");
                });

            modelBuilder.Entity("WinFormsApp1.Repositories.Models.Vehicle", b =>
                {
                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.Property<string>("ActualNb")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ActualNB");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AgeProp")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Brand")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Chassis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CityId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CityID");

                    b.Property<string>("CodeDesc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CodeDESC");

                    b.Property<string>("ColorDesc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Dateaquisition")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dateaquisition");

                    b.Property<string>("DistrictId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DistrictID");

                    b.Property<string>("GovernateId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GovernateID");

                    b.Property<int?>("Horsservice")
                        .HasColumnType("int")
                        .HasColumnName("HORSSERVICE");

                    b.Property<string>("Lastname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lastname");

                    b.Property<string>("Model")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MotherName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Motor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NoRegProp")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PreMiseCirc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Proddate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PRODDATE");

                    b.Property<int?>("SerialNb")
                        .HasColumnType("int")
                        .HasColumnName("serialNB");

                    b.Property<string>("TelProp")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UtilisDesc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Vid")
                        .HasName("PK__vehicles__DDB00C7DCC21BDC6");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("WinFormsApp1.Repositories.Models.Village", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int")
                        .HasColumnName("CODE");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("nchar(200)")
                        .HasColumnName("LABEL")
                        .IsFixedLength();

                    b.Property<int?>("Stat")
                        .HasColumnType("int")
                        .HasColumnName("STAT");

                    b.HasKey("Code")
                        .HasName("PK__Village__AA1D43782D41583B");

                    b.ToTable("Village");
                });

            modelBuilder.Entity("WinFormsApp1.Repositories.Models.Worldkey", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int")
                        .HasColumnName("CODE");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LABEL");

                    b.Property<int?>("Linkcode")
                        .HasColumnType("int")
                        .HasColumnName("LINKCODE");

                    b.Property<int?>("Office")
                        .HasColumnType("int")
                        .HasColumnName("OFFICE");

                    b.HasKey("Code")
                        .HasName("PK__worldkey__AA1D4378B6B2B618");

                    b.ToTable("worldkey");
                });
#pragma warning restore 612, 618
        }
    }
}
